### PR TITLE
Remove Timeout Option and Update Dependencies

### PR DESCRIPTION
**Pull request by nayefx64**
This pull request removes the timeout option from the Crawl4aiBasicCrawler node and updates dependencies.

The timeout option was deemed unnecessary as it can be controlled from the Crawl4ai API.

This change simplifies the node's configuration and aligns it with the API's capabilities. Additionally, this PR updates axios dependency to the latest version as well.

My current working env:

- Docker: 28.0.0
- n8n image: 1.94.1
- Crawl4AI image:  0.6.0-r1
- Node: 22.14.0

Working examples:

20f4r1pKz2
pkWg9iFrC6

Thanks to @golfamigo for compiling this beast together.

### CODE REVIEW

File: nodes/Crawl4aiBasicCrawler/helpers/apiClient.ts [hunk 1]
```diff
@@ -181,6 +180,10 @@ export class Crawl4aiClient {
         cache_mode: options.cacheMode || 'enabled',
         js_code: options.jsCode,
         css_selector: options.cssSelector,
+        viewport: {
```
Comment (nayefx64) [inline nodes/Crawl4aiBasicCrawler/helpers/apiClient.ts:183]: If you decided to merge, exclude this viewport block.

**Comment by venetanji** [comment]
How can I test this? seems i can't just npm i git+https.... in the official container's .n8n/nodes (only-allow pnpm).

**Comment by nayefx64** [comment]
Go to `/node_modules/n8n-nodes-crawl4ai`
`git clone https://github.com/nayefx64/n8n-nodes-crawl4ai.git`
`npm i`
`npm run build`
Restart n8n

**Comment by VladoPortos** [comment]
Still issue with:

```
[
{
"response": 
[
{
"url": 
"https://www.orsr.sk/vypis.asp?ID=363670&SID=2&P=0",
"success": 
false,
"error": 
"{\"error\": \"CrawlerRunConfig.__init__() got an unexpected keyword argument 'viewport'\", \"server_memory_delta_mb\": -0.14453125, \"server_peak_memory_mb\": 130.6796875}"
}
]
}
```

**Comment by elabbarw** [comment]
Bump. This node does not work with Crawl4AI V0.7.4. Timeout needs to be removed @golfamigo 

`[INIT].... → Crawl4AI 0.7.4
[2025-08-27 14:40:52 +0000] [13] [INFO] Application startup complete.
2025-08-27 14:44:22,032 - api - ERROR - Crawl error: BrowserConfig.__init__() got an unexpected keyword argument 'timeout'
Traceback (most recent call last):
  File "/app/api.py", line 432, in handle_crawl_request
    browser_config = BrowserConfig.load(browser_config)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/crawl4ai/async_configs.py", line 618, in load
    config = from_serializable_dict(data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/crawl4ai/async_configs.py", line 150, in from_serializable_dict
    return cls(**constructor_args)
           ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: BrowserConfig.__init__() got an unexpected keyword argument 'timeout'
2025-08-27 14:44:44,545 - api - ERROR - Crawl error: BrowserConfig.__init__() got an unexpected keyword argument 'timeout'
Traceback (most recent call last):
  File "/app/api.py", line 432, in handle_crawl_request
    browser_config = BrowserConfig.load(browser_config)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/crawl4ai/async_configs.py", line 618, in load
    config = from_serializable_dict(data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/crawl4ai/async_configs.py", line 150, in from_serializable_dict
    return cls(**constructor_args)
           ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: BrowserConfig.__init__() got an unexpected keyword argument 'timeout'`
